name: Update links.json

on:
  push:
    paths:
      - 'generate.html'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Extract new link from generate.html
        run: |
          NEW_LINK=$(grep 'data-link=' generate.html | sed -n 's/.*data-link="[^"]*.*/\1/p')
          echo "New link: $NEW_LINK"

          if [ -n "$NEW_LINK" ]; then
            jq --arg new_link "$NEW_LINK" '. + [$new_link]' links.json > temp.json && mv temp.json links.json
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add links.json
          git commit -m 'Add new link to links.json' || echo "No changes to commit"
          git push
